git-svn-id: file:///media/LinuxData/Development/SVN/StartupServices@9 27563164-11e0-4794-a12e-6657db1f5c2d

diff --git a/runservices b/runservices
--- a/runservices
+++ b/runservices
@@ -74,6 +74,9 @@ doRunService ()
 	local base command logfile pidfile runtype
 	local pid
 	local tries
+	local exitcode
+	local failed
+	local count
 
 	base=$1
 	command=$2
@@ -82,7 +85,7 @@ doRunService ()
 	runtype=$5
 
 #	echo " basename=$1, command=$2 log=$3, pidfile=$4, rt=$5"
-	echo " basename=$base, command=$command log=$logfile, pidfile=$pidfile, rt=$runtype"
+#	echo " basename=$base, command=$command log=$logfile, pidfile=$pidfile, rt=$runtype"
 
 	if [ "X$command" != "X" ];then
 		if [ -e "$pidfile" ];then
@@ -96,32 +99,39 @@ doRunService ()
 		fi
 
 		if [ $runtype = "once" ];then
-			($command) &>$logfile &
-			pid=$!
-
-			if [ "X$(ps --no-headers $pid)" = "X" ];then
-				tries=$RETRYS
-				echo "Error runing command $command ..."
-				while [ "X$(ps --no-headers $pid)" = "X" ]
-					do
-						for((j=1;j<RETRYS;j++))
-							do
-								($command) &>$logfile &
-								pid=$!
-								((tries--))
-								echo "$tries tries left ..."
-								sleep 1
-							done
-						echo "Can't run $base, giving up ..."
-						rm $pidfile &>/dev/null||true
-					done
+			failed=0
+			for ((j=0;j<RETRYS;j++))
+				do
+					$command &>$logfile &
+					pid=$!
+#check whether process is still running
+					count=$(ps -A| grep $pid |wc -l)
+#if process is already terminated, then there can be two cases, the process executed and stop successfully or it is terminated abnormally
+					if [[ $count -eq 0 ]];then
+#checks if process executed successfully or not
+						if wait $pid; then
+        		        	break;
+						else
+#process terminated abnormally
+							echo "Try $j failed (returned $?), Trying again ..."
+							failed=1
+						fi
+					else
+#process is still running
+						echo $pid > $pidfile
+						break
+					fi
+				done
+			if [ $failed -eq 1 ];then
+				echo "Giving up ..."
+			else
+				echo "$base launched succsefully"
 			fi
-			echo $pid > $pidfile
 		fi
 
 		if [ $runtype = "keepalive" ];then
 			touch ${SERVICERUNFILES}/${base}.keepalive
-			file=${SERVICERUNFILES}/${base}
+			file=${SERVICERUNFILES}/${base}.runfile
 			cat > $file << EOF
 #!/bin/bash
 	while [ -e ${base}.keepalive ]
@@ -133,7 +143,7 @@ doRunService ()
 		done
 EOF
 			chmod +x $file
-			(cd ${SERVICERUNFILES};./${base}) &
+			(cd ${SERVICERUNFILES};./${base}.runfile) &
 		fi
 	fi
 }
@@ -205,6 +215,15 @@ killAllServices ()
 		done < ${SERVICEDATA}/services
 }	
 
+printLogfile ()
+{
+		if [ -e  ${LOGSFOLDER}/${1}.log ];then
+			cat ${LOGSFOLDER}/${1}.log
+		else
+			echo "No log for $1 ..."
+		fi
+}
+
 main ()
 {
 	if [ "X$1" = "X" ];then
@@ -223,6 +242,9 @@ main ()
 				;;
 			"KILLALL")
 				killAllServices
+				;;
+			"LOGFILE")
+				printLogfile $2
 				;;
 		esac
 	fi
