git-svn-id: file:///media/LinuxData/Development/SVN/StartupServices@3 27563164-11e0-4794-a12e-6657db1f5c2d

diff --git a/runservices b/runservices
--- a/runservices
+++ b/runservices
@@ -1,10 +1,9 @@
-#!/bin/bash -e
+#!/bin/bash
 
 #©keithhedger Sat 4 Mar 15:35:56 GMT 2017 kdhedger68713@gmail.com
 
-
-SERVICEFOLDER=services
-SERVICEFILES=services
+SERVICEDATA=servicedata
+SERVICEFOLDER=servicefiles
 LOGFILE=
 COMMAND=
 RUNTYPE=
@@ -14,7 +13,6 @@ BASENAME=
 LOGSFOLDER=servicelogs
 RETRYS=3
 
-rm ${PIDFOLDER}/*.pid||true
 
 doService ()
 {
@@ -22,67 +20,109 @@ doService ()
 	local pid
 	local pidfile
 	local logfile
-
-	echo "log=$LOGFILE, rt=$RUNTYPE, command=$COMMAND, pidfile=$PIDFILE, basename=$BASENAME "
-return
+	local tries
 
 	if [ "X$COMMAND" != "X" ];then
-	echo "log=$LOGFILE, rt=$RUNTYPE, command=$COMMAND, pidfile=$PIDFILE, basename=$BASENAME "
+
+		if [ "X$LOGFILE" != "X" ];then
+			logfile=${LOGSFOLDER}/${LOGFILE}
+		else
+			logfile="/dev/null"
+		fi
+
+		if [ "X$PIDFILE" = "X" ];then
+			pidfile=${PIDFOLDER}/${BASENAME}.pid
+		fi
 
 
-	if [ "X$LOGFILE" != "X" ];then
-		logfile=${LOGSFOLDER}/${LOGFILE}
-	else
-		logfile="/dev/null"
-	fi
-
-	if [ "X$PIDFILE" = "X" ];then
-		pidfile=${PIDFOLDER}/${BASENAME}.pid
-	fi
-
-
-	
 	($COMMAND) &>$logfile &
 	pid=$!
 
-#
+	if [ "X$(ps --no-headers $pid)" = "X" ];then
+		tries=$RETRYS
+		echo "Error runing command $COMMAND ..."
+		while [ "X$(ps --no-headers $pid)" = "X" ]
+			do
+				for((j=1;j<RETRYS;j++))
+					do
+						($COMMAND) &>$logfile &
+						pid=$!
+						((tries--))
+						echo "$tries tries left ..."
+						sleep 1
+					done
+				echo "Can't run $BASENAME, giving up ..."
+				rm $pidfile &>/dev/null||true
+				return
+			done
+	fi
+			
+	echo XXXXXXXXxx
 	echo $pid > $pidfile
-#	echo $COMMAND
-#	echo $LOGFILE
-#	echo ">>>$pid"
+
+	echo "log=$LOGFILE, rt=$RUNTYPE, command=$COMMAND, pidfile=$pidfile, basename=$BASENAME "
 	fi
 }
 
-while read
-	do
-		echo $REPLY
-		BASENAME=${REPLY%%.?*}
-		LOGFILE=
-		COMMAND=
-		RUNTYPE=
-		PIDFILE=
+runAllServices ()
+{
+	rm ${PIDFOLDER}/*.pid||true
+	while read
+		do
+			echo $REPLY
+			BASENAME=${REPLY%%.?*}
+			LOGFILE=
+			COMMAND=
+			RUNTYPE=
+			PIDFILE=
 		
-		while read
-			do
-				#echo $REPLY
-				
-				COM=$(echo $REPLY|awk '{print $1}')
-				ARGS="$(echo -e "${REPLY:${#COM}:1000}" | sed -e 's/^[[:space:]]*//;s/[[:space:]]*$//')"
-				case "$COM" in
-					"LOGFILE")
-						LOGFILE=$ARGS
-						;;
-					"RUNTYPE")
-						RUNTYPE=$ARGS
-						;;
-					"COMMAND")
-						COMMAND=$ARGS
-						;;
-					"PIDFILE")
-						PIDFILE=$ARGS
-						;;
-				esac
-			done < ${SERVICEFOLDER}/$REPLY
-		doService
-	done < ${SERVICEFOLDER}/${SERVICEFILES}
-	
+			while read
+				do
+					COM=$(echo $REPLY|awk '{print $1}')
+					ARGS="$(echo -e "${REPLY:${#COM}:1000}" | sed -e 's/^[[:space:]]*//;s/[[:space:]]*$//')"
+					case "$COM" in
+						"LOGFILE")
+							LOGFILE=$ARGS
+							;;
+						"RUNTYPE")
+							RUNTYPE=$ARGS
+							;;
+						"COMMAND")
+							COMMAND=$ARGS
+							;;
+						"PIDFILE")
+							PIDFILE=$ARGS
+							;;
+					esac
+				done < ${SERVICEFOLDER}/$REPLY
+			doService
+		done < ${SERVICEDATA}/services
+}	
+
+killService ()
+{
+	kill -9 $(cat ${PIDFOLDER}/$1.pid)
+	rm  ${PIDFOLDER}/$1.pid
+}
+
+main ()
+{
+	if [ "X$1" = "X" ];then
+		echo "need command ..."
+		exit 1
+	else	
+		case $1 in
+			"RUNALL")
+				runAllServices;
+				;;
+			"KILL")
+				killService $2
+				;;
+		esac
+	fi
+}
+
+main $@
+
+
+
